name: curly_tribble
version: 0.0.1
description: Slide deck for polymer dart.
author: Matthew Butler <butler.matthew@gmail.com>
homepage: http://butlermatt.github.io/curly-tribble
dependencies:
  polymer: ^1.0.0-rc.5
  web_components: ^0.12.0+3
  reflectable: ^0.3.3
transformers:
  - web_components:
      entry_points: web/index.html
  - reflectable:
      entry_points: web/index.html
